"use strict";

const { ROLES } = require("./roles");

const PERMISSIONS = Object.freeze({
  RECRUITMENT_READ: "recruitment:read",
  RECRUITMENT_WRITE: "recruitment:write",
  RECRUITMENT_DELETE: "recruitment:delete",
  RECRUITMENT_RESTORE: "recruitment:restore",
  DRAFT_READ: "draft:read",
  DRAFT_WRITE: "draft:write",
  DRAFT_DELETE: "draft:delete",
  WORKFLOW_READ: "workflow:read",
  WORKFLOW_WRITE: "workflow:write",
  REVIEW_READ: "review:read",
  REVIEW_ASSIGN: "review:assign",
  REVIEW_DECIDE: "review:decide",
  AUDIT_READ: "audit:read",
  AUDIT_EXPORT: "audit:export",
  METRICS_READ: "metrics:read",
  SETTINGS_READ: "settings:read",
  SETTINGS_WRITE: "settings:write",
  SOURCE_READ: "source:read",
  SOURCE_WRITE: "source:write",
  AUTOMATION_EXECUTE: "automation:execute"
});

const PERMISSION_MATRIX = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.RECRUITMENT_WRITE,
    PERMISSIONS.RECRUITMENT_DELETE,
    PERMISSIONS.RECRUITMENT_RESTORE,
    PERMISSIONS.DRAFT_READ,
    PERMISSIONS.DRAFT_WRITE,
    PERMISSIONS.DRAFT_DELETE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_WRITE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.REVIEW_ASSIGN,
    PERMISSIONS.REVIEW_DECIDE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.METRICS_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.SOURCE_READ,
    PERMISSIONS.SOURCE_WRITE
  ],
  [ROLES.EDITOR]: [
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.RECRUITMENT_WRITE,
    PERMISSIONS.DRAFT_READ,
    PERMISSIONS.DRAFT_WRITE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.METRICS_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SOURCE_READ
  ],
  [ROLES.REVIEWER]: [
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.DRAFT_READ,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.REVIEW_ASSIGN,
    PERMISSIONS.REVIEW_DECIDE,
    PERMISSIONS.METRICS_READ,
    PERMISSIONS.AUDIT_READ
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.DRAFT_READ,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.METRICS_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SOURCE_READ
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.DRAFT_READ,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.METRICS_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SOURCE_READ
  ]
});

module.exports = {
  PERMISSIONS,
  PERMISSION_MATRIX
};
