"use strict";

/**
 * Phase AI-3 — Recruitment Matching & Recommendation taxonomy.
 *
 * Advisory-only vocabulary for deciding whether a normalized event (Phase AI-2)
 * belongs to an existing recruitment or represents a new one. Nothing in this
 * phase changes monitoring, the Production Workflow, publishing, or the
 * Generator: every output is a recommendation.
 */

const {
  CONFIDENCE_LEVELS,
  CONFIDENCE_THRESHOLDS,
  EVENT_TYPES,
  EVENT_SUB_TYPES,
  VALIDATION_SEVERITY
} = require("../noticeIntelligence/types");

const FORMAT_ID = "recruitment_matching_recommendation_v1";
const ENGINE_VERSION = "ai3.1.0";
const PHASE = "AI-3";

/** The only recommendations this engine is allowed to emit. */
const RECOMMENDATIONS = Object.freeze({
  CREATE_NEW: "CREATE_NEW",
  UPDATE_EXISTING: "UPDATE_EXISTING",
  MERGE_CANDIDATE: "MERGE_CANDIDATE",
  POSSIBLE_DUPLICATE: "POSSIBLE_DUPLICATE",
  HUMAN_REVIEW: "HUMAN_REVIEW",
  IGNORE: "IGNORE"
});

const RECOMMENDATION_LABELS = Object.freeze({
  [RECOMMENDATIONS.CREATE_NEW]: "Create a new recruitment",
  [RECOMMENDATIONS.UPDATE_EXISTING]: "Update an existing recruitment",
  [RECOMMENDATIONS.MERGE_CANDIDATE]: "Merge into an existing recruitment",
  [RECOMMENDATIONS.POSSIBLE_DUPLICATE]: "Possible duplicate of an already recorded document",
  [RECOMMENDATIONS.HUMAN_REVIEW]: "Send to human review",
  [RECOMMENDATIONS.IGNORE]: "Ignore — not a recruitment lifecycle event"
});

/** Update relationships an event can carry towards a recruitment. */
const UPDATE_RELATIONSHIPS = Object.freeze({
  NOTIFICATION: "notification",
  APPLY_ONLINE: "apply_online",
  CORRECTION: "correction",
  EXTENSION: "extension",
  ADMIT_CARD: "admit_card",
  EXAM_DATE: "exam_date",
  EXAM_CITY: "exam_city",
  ANSWER_KEY: "answer_key",
  RESULT: "result",
  FINAL_RESULT: "final_result",
  DV: "dv",
  JOINING: "joining",
  NONE: "none",
  UNKNOWN: "unknown"
});

const UPDATE_RELATIONSHIP_LABELS = Object.freeze({
  [UPDATE_RELATIONSHIPS.NOTIFICATION]: "Notification",
  [UPDATE_RELATIONSHIPS.APPLY_ONLINE]: "Apply Online",
  [UPDATE_RELATIONSHIPS.CORRECTION]: "Correction",
  [UPDATE_RELATIONSHIPS.EXTENSION]: "Extension",
  [UPDATE_RELATIONSHIPS.ADMIT_CARD]: "Admit Card",
  [UPDATE_RELATIONSHIPS.EXAM_DATE]: "Exam Date",
  [UPDATE_RELATIONSHIPS.EXAM_CITY]: "Exam City",
  [UPDATE_RELATIONSHIPS.ANSWER_KEY]: "Answer Key",
  [UPDATE_RELATIONSHIPS.RESULT]: "Result",
  [UPDATE_RELATIONSHIPS.FINAL_RESULT]: "Final Result",
  [UPDATE_RELATIONSHIPS.DV]: "Document Verification",
  [UPDATE_RELATIONSHIPS.JOINING]: "Joining",
  [UPDATE_RELATIONSHIPS.NONE]: "Not a recruitment update",
  [UPDATE_RELATIONSHIPS.UNKNOWN]: "Unrecognised update"
});

/**
 * Position in the recruitment lifecycle. Used to check that an update is
 * plausible for the recruitment it was matched to, and to describe how far a
 * recruitment has progressed.
 */
const RELATIONSHIP_ORDER = Object.freeze({
  [UPDATE_RELATIONSHIPS.NOTIFICATION]: 10,
  [UPDATE_RELATIONSHIPS.APPLY_ONLINE]: 20,
  [UPDATE_RELATIONSHIPS.CORRECTION]: 25,
  [UPDATE_RELATIONSHIPS.EXTENSION]: 26,
  [UPDATE_RELATIONSHIPS.EXAM_DATE]: 30,
  [UPDATE_RELATIONSHIPS.EXAM_CITY]: 35,
  [UPDATE_RELATIONSHIPS.ADMIT_CARD]: 40,
  [UPDATE_RELATIONSHIPS.ANSWER_KEY]: 50,
  [UPDATE_RELATIONSHIPS.RESULT]: 60,
  [UPDATE_RELATIONSHIPS.FINAL_RESULT]: 70,
  [UPDATE_RELATIONSHIPS.DV]: 80,
  [UPDATE_RELATIONSHIPS.JOINING]: 90,
  [UPDATE_RELATIONSHIPS.NONE]: 0,
  [UPDATE_RELATIONSHIPS.UNKNOWN]: 0
});

/**
 * Amendments legitimately appear at any point in the lifecycle, so they are
 * exempt from the backwards-transition plausibility check.
 */
const ANYTIME_RELATIONSHIPS = Object.freeze([
  UPDATE_RELATIONSHIPS.CORRECTION,
  UPDATE_RELATIONSHIPS.EXTENSION
]);

/** Relationships that only make sense against a recruitment that already exists. */
const DOWNSTREAM_RELATIONSHIPS = Object.freeze([
  UPDATE_RELATIONSHIPS.APPLY_ONLINE,
  UPDATE_RELATIONSHIPS.CORRECTION,
  UPDATE_RELATIONSHIPS.EXTENSION,
  UPDATE_RELATIONSHIPS.ADMIT_CARD,
  UPDATE_RELATIONSHIPS.EXAM_DATE,
  UPDATE_RELATIONSHIPS.EXAM_CITY,
  UPDATE_RELATIONSHIPS.ANSWER_KEY,
  UPDATE_RELATIONSHIPS.RESULT,
  UPDATE_RELATIONSHIPS.FINAL_RESULT,
  UPDATE_RELATIONSHIPS.DV,
  UPDATE_RELATIONSHIPS.JOINING
]);

/** Bridge from the Phase AI-2 event taxonomy to AI-3 update relationships. */
const EVENT_TYPE_TO_RELATIONSHIP = Object.freeze({
  [EVENT_TYPES.NEW_RECRUITMENT]: UPDATE_RELATIONSHIPS.NOTIFICATION,
  [EVENT_TYPES.NOTIFICATION]: UPDATE_RELATIONSHIPS.NOTIFICATION,
  [EVENT_TYPES.DETAILED_ADVERTISEMENT]: UPDATE_RELATIONSHIPS.NOTIFICATION,
  [EVENT_TYPES.SHORT_NOTICE]: UPDATE_RELATIONSHIPS.NOTIFICATION,
  [EVENT_TYPES.APPRENTICE]: UPDATE_RELATIONSHIPS.NOTIFICATION,
  [EVENT_TYPES.WALK_IN]: UPDATE_RELATIONSHIPS.NOTIFICATION,
  [EVENT_TYPES.CONTRACT_RECRUITMENT]: UPDATE_RELATIONSHIPS.NOTIFICATION,
  [EVENT_TYPES.RECRUITMENT_UPDATE]: UPDATE_RELATIONSHIPS.UNKNOWN,
  [EVENT_TYPES.APPLY_ONLINE]: UPDATE_RELATIONSHIPS.APPLY_ONLINE,
  [EVENT_TYPES.REGISTRATION_OPEN]: UPDATE_RELATIONSHIPS.APPLY_ONLINE,
  [EVENT_TYPES.REGISTRATION_CLOSE]: UPDATE_RELATIONSHIPS.APPLY_ONLINE,
  [EVENT_TYPES.CORRECTION]: UPDATE_RELATIONSHIPS.CORRECTION,
  [EVENT_TYPES.CORRIGENDUM]: UPDATE_RELATIONSHIPS.CORRECTION,
  [EVENT_TYPES.EXTENSION_NOTICE]: UPDATE_RELATIONSHIPS.EXTENSION,
  [EVENT_TYPES.EXAM_DATE]: UPDATE_RELATIONSHIPS.EXAM_DATE,
  [EVENT_TYPES.EXAM_CITY]: UPDATE_RELATIONSHIPS.EXAM_CITY,
  [EVENT_TYPES.ADMIT_CARD]: UPDATE_RELATIONSHIPS.ADMIT_CARD,
  [EVENT_TYPES.ANSWER_KEY]: UPDATE_RELATIONSHIPS.ANSWER_KEY,
  [EVENT_TYPES.OBJECTION_WINDOW]: UPDATE_RELATIONSHIPS.ANSWER_KEY,
  [EVENT_TYPES.RESULT]: UPDATE_RELATIONSHIPS.RESULT,
  [EVENT_TYPES.FINAL_RESULT]: UPDATE_RELATIONSHIPS.FINAL_RESULT,
  [EVENT_TYPES.DV_SCHEDULE]: UPDATE_RELATIONSHIPS.DV,
  [EVENT_TYPES.JOINING]: UPDATE_RELATIONSHIPS.JOINING,
  [EVENT_TYPES.CANCELLATION]: UPDATE_RELATIONSHIPS.UNKNOWN,
  [EVENT_TYPES.PRESS_RELEASE]: UPDATE_RELATIONSHIPS.NONE,
  [EVENT_TYPES.TENDER]: UPDATE_RELATIONSHIPS.NONE,
  [EVENT_TYPES.SCHOLARSHIP]: UPDATE_RELATIONSHIPS.NONE,
  [EVENT_TYPES.ADMISSION]: UPDATE_RELATIONSHIPS.NONE,
  [EVENT_TYPES.UNKNOWN]: UPDATE_RELATIONSHIPS.UNKNOWN
});

/**
 * A sub-type can refine the relationship when the primary type is generic —
 * a `result` carrying a `document_verification` qualifier is a DV schedule.
 */
const SUB_TYPE_TO_RELATIONSHIP = Object.freeze({
  [EVENT_SUB_TYPES.DOCUMENT_VERIFICATION]: UPDATE_RELATIONSHIPS.DV,
  [EVENT_SUB_TYPES.COUNSELLING]: UPDATE_RELATIONSHIPS.DV,
  [EVENT_SUB_TYPES.CITY_INTIMATION]: UPDATE_RELATIONSHIPS.EXAM_CITY,
  [EVENT_SUB_TYPES.FORM_CORRECTION]: UPDATE_RELATIONSHIPS.CORRECTION,
  [EVENT_SUB_TYPES.DATE_EXTENSION]: UPDATE_RELATIONSHIPS.EXTENSION,
  [EVENT_SUB_TYPES.FEE_DATE_EXTENSION]: UPDATE_RELATIONSHIPS.EXTENSION
});

/** Weighted factors used by the similarity engine. Weights sum to 1.00. */
const SIMILARITY_FACTORS = Object.freeze({
  ADVERTISEMENT_NUMBER: "advertisement_number",
  REFERENCE_NUMBER: "reference_number",
  BOARD: "board",
  DEPARTMENT: "department",
  TITLE: "title",
  YEAR: "year",
  KEYWORDS: "keywords",
  CATEGORY: "category"
});

const FACTOR_WEIGHTS = Object.freeze({
  [SIMILARITY_FACTORS.ADVERTISEMENT_NUMBER]: 0.29,
  [SIMILARITY_FACTORS.REFERENCE_NUMBER]: 0.19,
  [SIMILARITY_FACTORS.BOARD]: 0.13,
  [SIMILARITY_FACTORS.DEPARTMENT]: 0.06,
  [SIMILARITY_FACTORS.TITLE]: 0.17,
  [SIMILARITY_FACTORS.YEAR]: 0.08,
  [SIMILARITY_FACTORS.KEYWORDS]: 0.05,
  [SIMILARITY_FACTORS.CATEGORY]: 0.03
});

const FACTOR_STATUS = Object.freeze({
  MATCH: "match",
  PARTIAL: "partial",
  MISMATCH: "mismatch",
  NOT_COMPARABLE: "not_comparable"
});

/** Named, signed adjustments applied after the weighted average. */
const SIMILARITY_ADJUSTMENTS = Object.freeze({
  NO_IDENTIFIER_COMPARABLE: "NO_IDENTIFIER_COMPARABLE",
  IDENTIFIER_PARTIAL: "IDENTIFIER_PARTIAL",
  LOW_FACTOR_COVERAGE: "LOW_FACTOR_COVERAGE",
  YEAR_MISMATCH: "YEAR_MISMATCH",
  IDENTIFIER_CONFLICT_CAP: "IDENTIFIER_CONFLICT_CAP"
});

const ADJUSTMENT_VALUES = Object.freeze({
  NO_IDENTIFIER_COMPARABLE: -0.1,
  IDENTIFIER_PARTIAL: -0.04,
  LOW_FACTOR_COVERAGE: -0.12,
  YEAR_MISMATCH: -0.08
});

/** Similarity below which a factor set is considered to have thin coverage. */
const COVERAGE_FLOOR = 0.45;

/** A conflicting advertisement number can never produce more than this score. */
const IDENTIFIER_CONFLICT_CEILING = 0.55;

const MATCH_QUALITY = Object.freeze({
  STRONG: "STRONG",
  PROBABLE: "PROBABLE",
  WEAK: "WEAK",
  NONE: "NONE"
});

const MATCH_THRESHOLDS = Object.freeze({
  STRONG: 0.8,
  PROBABLE: 0.6,
  WEAK: 0.4
});

/** Two candidates closer than this are treated as indistinguishable. */
const AMBIGUITY_MARGIN = 0.06;

/** Blocking strategies used to pull candidates out of the recruitment index. */
const SEARCH_STRATEGIES = Object.freeze({
  ADVERTISEMENT_NUMBER: "advertisement_number",
  REFERENCE_NUMBER: "reference_number",
  OFFICIAL_IDENTIFIER: "official_identifier",
  RECRUITMENT_KEY: "recruitment_key",
  EXPLICIT_HINT: "explicit_hint",
  BOARD_AND_YEAR: "board_and_year",
  BOARD: "board",
  TITLE_TOKENS: "title_tokens",
  KEYWORDS: "keywords",
  CATEGORY_AND_YEAR: "category_and_year"
});

/** Strategies that key on an official identifier rather than on prose. */
const IDENTIFIER_STRATEGIES = Object.freeze([
  SEARCH_STRATEGIES.ADVERTISEMENT_NUMBER,
  SEARCH_STRATEGIES.REFERENCE_NUMBER,
  SEARCH_STRATEGIES.OFFICIAL_IDENTIFIER,
  SEARCH_STRATEGIES.RECRUITMENT_KEY
]);

const RECRUITMENT_CATEGORIES = Object.freeze({
  STATE_PSC: "state_psc",
  UNION_PSC: "union_psc",
  SSC: "ssc",
  RAILWAY: "railway",
  POLICE: "police",
  DEFENCE: "defence",
  BANKING: "banking",
  TEACHING: "teaching",
  MEDICAL: "medical",
  UNIVERSITY: "university",
  SUBORDINATE_SERVICE: "subordinate_service",
  APPRENTICE: "apprentice",
  OTHER: "other",
  UNKNOWN: "unknown"
});

const VALIDATION_CODES = Object.freeze({
  MULTIPLE_STRONG_MATCHES: "MULTIPLE_STRONG_MATCHES",
  MISSING_ADVERTISEMENT_NUMBER: "MISSING_ADVERTISEMENT_NUMBER",
  CONFLICTING_DEPARTMENTS: "CONFLICTING_DEPARTMENTS",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
  AMBIGUOUS_TITLE: "AMBIGUOUS_TITLE",
  IDENTIFIER_CONFLICT: "IDENTIFIER_CONFLICT",
  YEAR_MISMATCH_ON_MATCHING_TITLE: "YEAR_MISMATCH_ON_MATCHING_TITLE",
  ORPHAN_UPDATE_EVENT: "ORPHAN_UPDATE_EVENT",
  IMPLAUSIBLE_LIFECYCLE_TRANSITION: "IMPLAUSIBLE_LIFECYCLE_TRANSITION",
  NO_CANDIDATES_FOUND: "NO_CANDIDATES_FOUND",
  EMPTY_RECRUITMENT_REPOSITORY: "EMPTY_RECRUITMENT_REPOSITORY",
  DUPLICATE_DOCUMENT_FINGERPRINT: "DUPLICATE_DOCUMENT_FINGERPRINT",
  NON_RECRUITMENT_EVENT: "NON_RECRUITMENT_EVENT",
  UNRESOLVED_UPDATE_RELATIONSHIP: "UNRESOLVED_UPDATE_RELATIONSHIP"
});

/** Reason codes attached to confidence scores and recommendations. */
const REASON_CODES = Object.freeze({
  EXACT_ADVERTISEMENT_NUMBER: "EXACT_ADVERTISEMENT_NUMBER",
  EXACT_REFERENCE_NUMBER: "EXACT_REFERENCE_NUMBER",
  IDENTIFIER_BLOCKED: "IDENTIFIER_BLOCKED",
  BOARD_AND_YEAR_BLOCKED: "BOARD_AND_YEAR_BLOCKED",
  TITLE_TOKEN_BLOCKED: "TITLE_TOKEN_BLOCKED",
  KEYWORD_BLOCKED: "KEYWORD_BLOCKED",
  SINGLE_CANDIDATE: "SINGLE_CANDIDATE",
  CLEAR_SEPARATION: "CLEAR_SEPARATION",
  TIGHT_SEPARATION: "TIGHT_SEPARATION",
  MANY_CANDIDATES: "MANY_CANDIDATES",
  NO_CANDIDATES: "NO_CANDIDATES",
  EMPTY_REPOSITORY: "EMPTY_REPOSITORY",
  MATCH_SIMILARITY: "MATCH_SIMILARITY",
  TITLE_STRONG: "TITLE_STRONG",
  TITLE_WEAK: "TITLE_WEAK",
  LIFECYCLE_PLAUSIBLE: "LIFECYCLE_PLAUSIBLE",
  LIFECYCLE_IMPLAUSIBLE: "LIFECYCLE_IMPLAUSIBLE",
  IDENTIFIER_CONFLICT: "IDENTIFIER_CONFLICT",
  NO_IDENTIFIER: "NO_IDENTIFIER",
  YEAR_MISMATCH: "YEAR_MISMATCH",
  DEPARTMENT_CONFLICT: "DEPARTMENT_CONFLICT",
  RULE_BASE_CONFIDENCE: "RULE_BASE_CONFIDENCE",
  MATCH_QUALITY_SUPPORT: "MATCH_QUALITY_SUPPORT",
  CANDIDATE_SELECTION_SUPPORT: "CANDIDATE_SELECTION_SUPPORT",
  EVENT_CONFIDENCE_LOW: "EVENT_CONFIDENCE_LOW",
  EVENT_CONFIDENCE_HIGH: "EVENT_CONFIDENCE_HIGH",
  VALIDATION_FLAGS: "VALIDATION_FLAGS",
  AMBIGUOUS_TITLE: "AMBIGUOUS_TITLE"
});

/** Identifiers of the ordered decision rules in the recommendation engine. */
const RULE_IDS = Object.freeze({
  NON_RECRUITMENT_EVENT: "NON_RECRUITMENT_EVENT",
  UNIDENTIFIABLE_EVENT: "UNIDENTIFIABLE_EVENT",
  VERY_LOW_EVENT_CONFIDENCE: "VERY_LOW_EVENT_CONFIDENCE",
  DUPLICATE_OF_RECORDED_DOCUMENT: "DUPLICATE_OF_RECORDED_DOCUMENT",
  AMBIGUOUS_MULTIPLE_STRONG_MATCHES: "AMBIGUOUS_MULTIPLE_STRONG_MATCHES",
  DEPARTMENT_CONFLICT_ON_MATCH: "DEPARTMENT_CONFLICT_ON_MATCH",
  IMPLAUSIBLE_LIFECYCLE_ON_MATCH: "IMPLAUSIBLE_LIFECYCLE_ON_MATCH",
  NEW_CYCLE_OF_KNOWN_RECRUITMENT: "NEW_CYCLE_OF_KNOWN_RECRUITMENT",
  STRONG_MATCH_UPDATE: "STRONG_MATCH_UPDATE",
  STRONG_MATCH_ANNOUNCEMENT: "STRONG_MATCH_ANNOUNCEMENT",
  STRONG_MATCH_UNRESOLVED_RELATIONSHIP: "STRONG_MATCH_UNRESOLVED_RELATIONSHIP",
  PROBABLE_MATCH_WITH_IDENTIFIER: "PROBABLE_MATCH_WITH_IDENTIFIER",
  PROBABLE_MATCH_WITHOUT_IDENTIFIER: "PROBABLE_MATCH_WITHOUT_IDENTIFIER",
  IDENTIFIER_CONFLICT_ON_UPDATE: "IDENTIFIER_CONFLICT_ON_UPDATE",
  ORPHAN_UPDATE_EVENT: "ORPHAN_UPDATE_EVENT",
  NO_MATCH_NEW_RECRUITMENT: "NO_MATCH_NEW_RECRUITMENT",
  WEAK_MATCH_NEW_RECRUITMENT: "WEAK_MATCH_NEW_RECRUITMENT",
  UNRESOLVED_RELATIONSHIP: "UNRESOLVED_RELATIONSHIP",
  INSUFFICIENT_EVIDENCE: "INSUFFICIENT_EVIDENCE"
});

module.exports = {
  FORMAT_ID,
  ENGINE_VERSION,
  PHASE,
  RECOMMENDATIONS,
  RECOMMENDATION_LABELS,
  UPDATE_RELATIONSHIPS,
  UPDATE_RELATIONSHIP_LABELS,
  RELATIONSHIP_ORDER,
  ANYTIME_RELATIONSHIPS,
  DOWNSTREAM_RELATIONSHIPS,
  EVENT_TYPE_TO_RELATIONSHIP,
  SUB_TYPE_TO_RELATIONSHIP,
  SIMILARITY_FACTORS,
  FACTOR_WEIGHTS,
  FACTOR_STATUS,
  SIMILARITY_ADJUSTMENTS,
  ADJUSTMENT_VALUES,
  COVERAGE_FLOOR,
  IDENTIFIER_CONFLICT_CEILING,
  MATCH_QUALITY,
  MATCH_THRESHOLDS,
  AMBIGUITY_MARGIN,
  SEARCH_STRATEGIES,
  IDENTIFIER_STRATEGIES,
  RECRUITMENT_CATEGORIES,
  VALIDATION_CODES,
  REASON_CODES,
  RULE_IDS,
  // Re-exported from Phase AI-2 so both phases speak one vocabulary.
  CONFIDENCE_LEVELS,
  CONFIDENCE_THRESHOLDS,
  VALIDATION_SEVERITY
};
