"use strict";

/**
 * PWP Phase 4 — Editorial Workflow taxonomy.
 * Deterministic constants only. No AI. No publishing. No HTML.
 */

const ENGINE_ID = "PWP_EDITORIAL_WORKFLOW_LAYER";
const ENGINE_VERSION = "1.0.0";
const PHASE = "PHASE_4";
const EDITORIAL_PACKAGE_FORMAT_ID = "pwp_editorial_package_v1";
const EDITORIAL_CONTRACT_FORMAT_ID = "pwp_editorial_contract_v1";

/** Deterministic review states. */
const REVIEW_STATES = Object.freeze({
  QUEUED: "QUEUED",
  UNDER_REVIEW: "UNDER_REVIEW",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  READY_FOR_MANUAL_PUBLISH: "READY_FOR_MANUAL_PUBLISH"
});

/** Explicit review actions — no automatic approval. */
const REVIEW_ACTIONS = Object.freeze({
  START_REVIEW: "START_REVIEW",
  REQUEST_CHANGES: "REQUEST_CHANGES",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
  RETURN_TO_QUEUE: "RETURN_TO_QUEUE",
  MARK_READY_FOR_MANUAL_PUBLISH: "MARK_READY_FOR_MANUAL_PUBLISH"
});

/**
 * Allowed transitions: action → { fromState → toState }.
 * Every transition must be requested explicitly.
 */
const REVIEW_TRANSITIONS = Object.freeze({
  [REVIEW_ACTIONS.START_REVIEW]: Object.freeze({
    [REVIEW_STATES.QUEUED]: REVIEW_STATES.UNDER_REVIEW,
    [REVIEW_STATES.CHANGES_REQUESTED]: REVIEW_STATES.UNDER_REVIEW
  }),
  [REVIEW_ACTIONS.REQUEST_CHANGES]: Object.freeze({
    [REVIEW_STATES.UNDER_REVIEW]: REVIEW_STATES.CHANGES_REQUESTED
  }),
  [REVIEW_ACTIONS.APPROVE]: Object.freeze({
    [REVIEW_STATES.UNDER_REVIEW]: REVIEW_STATES.APPROVED
  }),
  [REVIEW_ACTIONS.REJECT]: Object.freeze({
    [REVIEW_STATES.QUEUED]: REVIEW_STATES.REJECTED,
    [REVIEW_STATES.UNDER_REVIEW]: REVIEW_STATES.REJECTED,
    [REVIEW_STATES.CHANGES_REQUESTED]: REVIEW_STATES.REJECTED
  }),
  [REVIEW_ACTIONS.RETURN_TO_QUEUE]: Object.freeze({
    [REVIEW_STATES.UNDER_REVIEW]: REVIEW_STATES.QUEUED,
    [REVIEW_STATES.CHANGES_REQUESTED]: REVIEW_STATES.QUEUED,
    [REVIEW_STATES.APPROVED]: REVIEW_STATES.QUEUED
  }),
  [REVIEW_ACTIONS.MARK_READY_FOR_MANUAL_PUBLISH]: Object.freeze({
    [REVIEW_STATES.APPROVED]: REVIEW_STATES.READY_FOR_MANUAL_PUBLISH
  })
});

/** Terminal states — no further transitions except as listed above. */
const TERMINAL_REVIEW_STATES = Object.freeze([
  REVIEW_STATES.REJECTED,
  REVIEW_STATES.READY_FOR_MANUAL_PUBLISH
]);

module.exports = {
  ENGINE_ID,
  ENGINE_VERSION,
  PHASE,
  EDITORIAL_PACKAGE_FORMAT_ID,
  EDITORIAL_CONTRACT_FORMAT_ID,
  REVIEW_STATES,
  REVIEW_ACTIONS,
  REVIEW_TRANSITIONS,
  TERMINAL_REVIEW_STATES
};
