"use strict";

/**
 * Phase AI-4 — Editorial Intelligence & Draft Quality taxonomy.
 *
 * Advisory-only vocabulary for analysing Generator drafts before they reach
 * the Editorial Review Queue. Nothing in this phase publishes, mutates drafts,
 * changes the Generator UI, Production Workflow, Monitoring, or AUTO_PUBLISH.
 */

const {
  SECTION_TYPES,
  SECTION_TYPE_TO_TITLE,
  LINK_CATEGORIES,
  LINK_CATEGORY_TO_LABEL
} = require("../generatorIntelligence/types");

const {
  CONFIDENCE_LEVELS,
  CONFIDENCE_THRESHOLDS,
  EVENT_TYPES,
  VALIDATION_SEVERITY: AI2_VALIDATION_SEVERITY
} = require("../noticeIntelligence/types");

const FORMAT_ID = "editorial_intelligence_report_v1";
const ENGINE_VERSION = "ai4.1.0";
const PHASE = "AI-4";

/** Severity for missing-info and validation findings shown to editors. */
const SEVERITY = Object.freeze({
  CRITICAL: "Critical",
  HIGH: "High",
  MEDIUM: "Medium",
  LOW: "Low"
});

/** Map AI-2 validation severity onto editorial severity when bridging. */
const VALIDATION_SEVERITY = Object.freeze({
  ...AI2_VALIDATION_SEVERITY,
  CRITICAL: "CRITICAL",
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW"
});

const QUALITY_DIMENSIONS = Object.freeze({
  COMPLETENESS: "completeness",
  CONSISTENCY: "consistency",
  READABILITY: "readability",
  STRUCTURE: "structure",
  LINK_QUALITY: "linkQuality",
  SECTION_COVERAGE: "sectionCoverage",
  OVERALL: "overall"
});

const SUGGESTION_TYPES = Object.freeze({
  ADD_SECTION: "add_section",
  ADD_CONTENT: "add_content",
  MOVE_SECTION: "move_section",
  MERGE_PARAGRAPHS: "merge_duplicate_paragraphs",
  REMOVE_DUPLICATE_DATES: "remove_duplicate_dates",
  CORRECT_TERMINOLOGY: "correct_inconsistent_terminology",
  CONVERT_TO_TABLE: "convert_paragraph_to_table",
  CONVERT_TO_BULLETS: "convert_paragraph_to_bullet_list",
  RENAME_SECTION: "recommend_clearer_section_title",
  FIX_LINK: "fix_link",
  REMOVE_DUPLICATE_LINK: "remove_duplicate_link",
  FIX_LANGUAGE: "improve_language",
  FIX_FORMATTING: "fix_formatting",
  REORDER_SECTIONS: "reorder_sections",
  RESOLVE_INCONSISTENCY: "resolve_inconsistency"
});

const EFFORT_LEVELS = Object.freeze({
  MINIMAL: "minimal",
  LIGHT: "light",
  MODERATE: "moderate",
  SUBSTANTIAL: "substantial",
  HEAVY: "heavy"
});

/**
 * Canonical sections evaluated for completeness on a full recruitment draft.
 * Unknown sections are always preserved and never score as missing.
 */
const COMPLETENESS_SECTIONS = Object.freeze([
  SECTION_TYPES.SHORT_INFORMATION,
  SECTION_TYPES.IMPORTANT_DATES,
  SECTION_TYPES.APPLICATION_FEE,
  SECTION_TYPES.AGE_LIMIT,
  SECTION_TYPES.VACANCY_DETAILS,
  SECTION_TYPES.ELIGIBILITY,
  SECTION_TYPES.SELECTION_PROCESS,
  SECTION_TYPES.SALARY,
  SECTION_TYPES.HOW_TO_APPLY,
  SECTION_TYPES.IMPORTANT_LINKS,
  SECTION_TYPES.FAQ,
  SECTION_TYPES.HELPLINE,
  SECTION_TYPES.NOTIFICATION_DETAILS,
  SECTION_TYPES.IMPORTANT_INSTRUCTIONS
]);

/**
 * Preferred Generator section order for a full recruitment page.
 * Unknown / extra sections keep relative order after known ones they follow.
 */
const PREFERRED_SECTION_ORDER = Object.freeze([
  SECTION_TYPES.SHORT_INFORMATION,
  SECTION_TYPES.IMPORTANT_DATES,
  SECTION_TYPES.APPLICATION_FEE,
  SECTION_TYPES.AGE_LIMIT,
  SECTION_TYPES.VACANCY_DETAILS,
  SECTION_TYPES.ELIGIBILITY,
  SECTION_TYPES.QUALIFICATION,
  SECTION_TYPES.SELECTION_PROCESS,
  SECTION_TYPES.EXAM_PATTERN,
  SECTION_TYPES.SYLLABUS,
  SECTION_TYPES.SALARY,
  SECTION_TYPES.HOW_TO_APPLY,
  SECTION_TYPES.IMPORTANT_LINKS,
  SECTION_TYPES.FAQ,
  SECTION_TYPES.HELPLINE,
  SECTION_TYPES.NOTIFICATION_DETAILS,
  SECTION_TYPES.IMPORTANT_INSTRUCTIONS
]);

/**
 * Draft / event profiles change which sections and links are expected.
 * Profiles are advisory expectations only.
 */
const DRAFT_PROFILES = Object.freeze({
  NEW_RECRUITMENT: "new_recruitment",
  ADMIT_CARD: "admit_card",
  RESULT: "result",
  CORRECTION: "correction",
  EXTENSION: "extension",
  ANSWER_KEY: "answer_key",
  GENERIC_UPDATE: "generic_update",
  UNKNOWN: "unknown"
});

const PROFILE_EXPECTED_SECTIONS = Object.freeze({
  [DRAFT_PROFILES.NEW_RECRUITMENT]: COMPLETENESS_SECTIONS,
  [DRAFT_PROFILES.ADMIT_CARD]: Object.freeze([
    SECTION_TYPES.SHORT_INFORMATION,
    SECTION_TYPES.IMPORTANT_DATES,
    SECTION_TYPES.HOW_TO_APPLY,
    SECTION_TYPES.IMPORTANT_LINKS,
    SECTION_TYPES.IMPORTANT_INSTRUCTIONS,
    SECTION_TYPES.HELPLINE
  ]),
  [DRAFT_PROFILES.RESULT]: Object.freeze([
    SECTION_TYPES.SHORT_INFORMATION,
    SECTION_TYPES.IMPORTANT_DATES,
    SECTION_TYPES.IMPORTANT_LINKS,
    SECTION_TYPES.IMPORTANT_INSTRUCTIONS,
    SECTION_TYPES.HELPLINE
  ]),
  [DRAFT_PROFILES.CORRECTION]: Object.freeze([
    SECTION_TYPES.SHORT_INFORMATION,
    SECTION_TYPES.IMPORTANT_DATES,
    SECTION_TYPES.IMPORTANT_LINKS,
    SECTION_TYPES.IMPORTANT_INSTRUCTIONS,
    SECTION_TYPES.NOTIFICATION_DETAILS
  ]),
  [DRAFT_PROFILES.EXTENSION]: Object.freeze([
    SECTION_TYPES.SHORT_INFORMATION,
    SECTION_TYPES.IMPORTANT_DATES,
    SECTION_TYPES.APPLICATION_FEE,
    SECTION_TYPES.HOW_TO_APPLY,
    SECTION_TYPES.IMPORTANT_LINKS,
    SECTION_TYPES.IMPORTANT_INSTRUCTIONS
  ]),
  [DRAFT_PROFILES.ANSWER_KEY]: Object.freeze([
    SECTION_TYPES.SHORT_INFORMATION,
    SECTION_TYPES.IMPORTANT_DATES,
    SECTION_TYPES.IMPORTANT_LINKS,
    SECTION_TYPES.IMPORTANT_INSTRUCTIONS
  ]),
  [DRAFT_PROFILES.GENERIC_UPDATE]: Object.freeze([
    SECTION_TYPES.SHORT_INFORMATION,
    SECTION_TYPES.IMPORTANT_DATES,
    SECTION_TYPES.IMPORTANT_LINKS
  ]),
  [DRAFT_PROFILES.UNKNOWN]: Object.freeze([
    SECTION_TYPES.SHORT_INFORMATION,
    SECTION_TYPES.IMPORTANT_LINKS
  ])
});

const PROFILE_EXPECTED_LINKS = Object.freeze({
  [DRAFT_PROFILES.NEW_RECRUITMENT]: Object.freeze([
    LINK_CATEGORIES.NOTIFICATION_PDF,
    LINK_CATEGORIES.APPLY_ONLINE,
    LINK_CATEGORIES.OFFICIAL_WEBSITE
  ]),
  [DRAFT_PROFILES.ADMIT_CARD]: Object.freeze([
    LINK_CATEGORIES.ADMIT_CARD,
    LINK_CATEGORIES.OFFICIAL_WEBSITE,
    LINK_CATEGORIES.LOGIN
  ]),
  [DRAFT_PROFILES.RESULT]: Object.freeze([
    LINK_CATEGORIES.RESULT,
    LINK_CATEGORIES.OFFICIAL_WEBSITE
  ]),
  [DRAFT_PROFILES.CORRECTION]: Object.freeze([
    LINK_CATEGORIES.CORRECTION,
    LINK_CATEGORIES.OFFICIAL_WEBSITE,
    LINK_CATEGORIES.NOTIFICATION_PDF
  ]),
  [DRAFT_PROFILES.EXTENSION]: Object.freeze([
    LINK_CATEGORIES.APPLY_ONLINE,
    LINK_CATEGORIES.OFFICIAL_WEBSITE,
    LINK_CATEGORIES.NOTIFICATION_PDF
  ]),
  [DRAFT_PROFILES.ANSWER_KEY]: Object.freeze([
    LINK_CATEGORIES.ANSWER_KEY,
    LINK_CATEGORIES.OFFICIAL_WEBSITE
  ]),
  [DRAFT_PROFILES.GENERIC_UPDATE]: Object.freeze([LINK_CATEGORIES.OFFICIAL_WEBSITE]),
  [DRAFT_PROFILES.UNKNOWN]: Object.freeze([LINK_CATEGORIES.OFFICIAL_WEBSITE])
});

/** Bridge AI-2 event types onto draft profiles. */
const EVENT_TYPE_TO_PROFILE = Object.freeze({
  [EVENT_TYPES.NEW_RECRUITMENT]: DRAFT_PROFILES.NEW_RECRUITMENT,
  [EVENT_TYPES.NOTIFICATION]: DRAFT_PROFILES.NEW_RECRUITMENT,
  [EVENT_TYPES.DETAILED_ADVERTISEMENT]: DRAFT_PROFILES.NEW_RECRUITMENT,
  [EVENT_TYPES.SHORT_NOTICE]: DRAFT_PROFILES.NEW_RECRUITMENT,
  [EVENT_TYPES.APPRENTICE]: DRAFT_PROFILES.NEW_RECRUITMENT,
  [EVENT_TYPES.WALK_IN]: DRAFT_PROFILES.NEW_RECRUITMENT,
  [EVENT_TYPES.CONTRACT_RECRUITMENT]: DRAFT_PROFILES.NEW_RECRUITMENT,
  [EVENT_TYPES.ADMIT_CARD]: DRAFT_PROFILES.ADMIT_CARD,
  [EVENT_TYPES.RESULT]: DRAFT_PROFILES.RESULT,
  [EVENT_TYPES.FINAL_RESULT]: DRAFT_PROFILES.RESULT,
  [EVENT_TYPES.CORRECTION]: DRAFT_PROFILES.CORRECTION,
  [EVENT_TYPES.CORRIGENDUM]: DRAFT_PROFILES.CORRECTION,
  [EVENT_TYPES.EXTENSION_NOTICE]: DRAFT_PROFILES.EXTENSION,
  [EVENT_TYPES.ANSWER_KEY]: DRAFT_PROFILES.ANSWER_KEY,
  [EVENT_TYPES.OBJECTION_WINDOW]: DRAFT_PROFILES.ANSWER_KEY,
  [EVENT_TYPES.APPLY_ONLINE]: DRAFT_PROFILES.GENERIC_UPDATE,
  [EVENT_TYPES.REGISTRATION_OPEN]: DRAFT_PROFILES.GENERIC_UPDATE,
  [EVENT_TYPES.EXAM_DATE]: DRAFT_PROFILES.GENERIC_UPDATE,
  [EVENT_TYPES.EXAM_CITY]: DRAFT_PROFILES.GENERIC_UPDATE,
  [EVENT_TYPES.DV_SCHEDULE]: DRAFT_PROFILES.GENERIC_UPDATE,
  [EVENT_TYPES.RECRUITMENT_UPDATE]: DRAFT_PROFILES.GENERIC_UPDATE
});

const VALIDATION_CODES = Object.freeze({
  DATE_MISSING_FROM_IMPORTANT_DATES: "DATE_MISSING_FROM_IMPORTANT_DATES",
  FEE_VALUE_MISMATCH: "FEE_VALUE_MISMATCH",
  VACANCY_TOTAL_MISMATCH: "VACANCY_TOTAL_MISMATCH",
  ELIGIBILITY_QUALIFICATION_CONFLICT: "ELIGIBILITY_QUALIFICATION_CONFLICT",
  LINK_EVENT_TYPE_MISMATCH: "LINK_EVENT_TYPE_MISMATCH",
  REFERENCE_NUMBER_INCONSISTENT: "REFERENCE_NUMBER_INCONSISTENT",
  ADVERTISEMENT_NUMBER_INCONSISTENT: "ADVERTISEMENT_NUMBER_INCONSISTENT",
  DUPLICATE_DATE_ENTRIES: "DUPLICATE_DATE_ENTRIES",
  DUPLICATE_LINK: "DUPLICATE_LINK",
  BROKEN_OR_PLACEHOLDER_LINK: "BROKEN_OR_PLACEHOLDER_LINK",
  SECTION_OUT_OF_ORDER: "SECTION_OUT_OF_ORDER",
  EMPTY_SECTION: "EMPTY_SECTION",
  TERMINOLOGY_INCONSISTENT: "TERMINOLOGY_INCONSISTENT"
});

const MISSING_CODES = Object.freeze({
  MISSING_APPLICATION_START_DATE: "MISSING_APPLICATION_START_DATE",
  MISSING_LAST_DATE: "MISSING_LAST_DATE",
  MISSING_AGE_CALCULATION_DATE: "MISSING_AGE_CALCULATION_DATE",
  MISSING_FEE_SECTION: "MISSING_FEE_SECTION",
  MISSING_OFFICIAL_NOTIFICATION_LINK: "MISSING_OFFICIAL_NOTIFICATION_LINK",
  MISSING_OFFICIAL_WEBSITE: "MISSING_OFFICIAL_WEBSITE",
  MISSING_SELECTION_PROCESS: "MISSING_SELECTION_PROCESS",
  MISSING_SALARY: "MISSING_SALARY",
  MISSING_FAQ: "MISSING_FAQ",
  MISSING_SHORT_INFORMATION: "MISSING_SHORT_INFORMATION",
  MISSING_VACANCY_DETAILS: "MISSING_VACANCY_DETAILS",
  MISSING_ELIGIBILITY: "MISSING_ELIGIBILITY",
  MISSING_HOW_TO_APPLY: "MISSING_HOW_TO_APPLY",
  MISSING_IMPORTANT_DATES: "MISSING_IMPORTANT_DATES",
  MISSING_HELPLINE: "MISSING_HELPLINE",
  MISSING_APPLY_ONLINE_LINK: "MISSING_APPLY_ONLINE_LINK",
  MISSING_ADMIT_CARD_LINK: "MISSING_ADMIT_CARD_LINK",
  MISSING_RESULT_LINK: "MISSING_RESULT_LINK",
  MISSING_CORRECTION_LINK: "MISSING_CORRECTION_LINK",
  MISSING_ANSWER_KEY_LINK: "MISSING_ANSWER_KEY_LINK"
});

const LANGUAGE_ISSUE_CODES = Object.freeze({
  MIXED_HINDI_ENGLISH: "MIXED_HINDI_ENGLISH",
  BROKEN_UNICODE: "BROKEN_UNICODE",
  REPEATED_SENTENCES: "REPEATED_SENTENCES",
  OCR_ARTIFACTS: "OCR_ARTIFACTS",
  FORMATTING_PROBLEMS: "FORMATTING_PROBLEMS"
});

/** Score weights for overall editorial quality (sum = 1.00). */
const SCORE_WEIGHTS = Object.freeze({
  [QUALITY_DIMENSIONS.COMPLETENESS]: 0.22,
  [QUALITY_DIMENSIONS.CONSISTENCY]: 0.2,
  [QUALITY_DIMENSIONS.READABILITY]: 0.12,
  [QUALITY_DIMENSIONS.STRUCTURE]: 0.14,
  [QUALITY_DIMENSIONS.LINK_QUALITY]: 0.16,
  [QUALITY_DIMENSIONS.SECTION_COVERAGE]: 0.16
});

module.exports = {
  FORMAT_ID,
  ENGINE_VERSION,
  PHASE,
  SEVERITY,
  VALIDATION_SEVERITY,
  QUALITY_DIMENSIONS,
  SUGGESTION_TYPES,
  EFFORT_LEVELS,
  COMPLETENESS_SECTIONS,
  PREFERRED_SECTION_ORDER,
  DRAFT_PROFILES,
  PROFILE_EXPECTED_SECTIONS,
  PROFILE_EXPECTED_LINKS,
  EVENT_TYPE_TO_PROFILE,
  VALIDATION_CODES,
  MISSING_CODES,
  LANGUAGE_ISSUE_CODES,
  SCORE_WEIGHTS,
  SECTION_TYPES,
  SECTION_TYPE_TO_TITLE,
  LINK_CATEGORIES,
  LINK_CATEGORY_TO_LABEL,
  CONFIDENCE_LEVELS,
  CONFIDENCE_THRESHOLDS,
  EVENT_TYPES
};
