"use strict";

/**
 * PWP Phase 1 + Phase 2 — Deterministic workflow state model.
 * Transitions are logged by the workflow engine. No persistence.
 */

const WORKFLOW_STATES = Object.freeze({
  SOURCE_DETECTED: "SOURCE_DETECTED",
  CHANGE_DETECTED: "CHANGE_DETECTED",
  SOURCE_PROFILED: "SOURCE_PROFILED",
  CONTENT_EXTRACTED: "CONTENT_EXTRACTED",
  CONTENT_CORRELATED: "CONTENT_CORRELATED",
  QUALITY_VALIDATED: "QUALITY_VALIDATED",
  RECRUITMENT_RESOLVED: "RECRUITMENT_RESOLVED",
  DOCUMENT_ANALYZED: "DOCUMENT_ANALYZED",
  AI_PREPARED: "AI_PREPARED",
  DRAFT_CREATED: "DRAFT_CREATED",
  EDITORIAL_QUEUED: "EDITORIAL_QUEUED",
  TELEGRAM_NOTIFIED: "TELEGRAM_NOTIFIED",
  READY_FOR_REVIEW: "READY_FOR_REVIEW",
  PUBLISHED_MANUALLY: "PUBLISHED_MANUALLY",
  FAILED: "FAILED"
});

/** Ordered happy-path stages (FAILED is terminal / error only). */
const STATE_SEQUENCE = Object.freeze([
  WORKFLOW_STATES.SOURCE_DETECTED,
  WORKFLOW_STATES.CHANGE_DETECTED,
  WORKFLOW_STATES.SOURCE_PROFILED,
  WORKFLOW_STATES.CONTENT_EXTRACTED,
  WORKFLOW_STATES.CONTENT_CORRELATED,
  WORKFLOW_STATES.QUALITY_VALIDATED,
  WORKFLOW_STATES.RECRUITMENT_RESOLVED,
  WORKFLOW_STATES.DOCUMENT_ANALYZED,
  WORKFLOW_STATES.AI_PREPARED,
  WORKFLOW_STATES.DRAFT_CREATED,
  WORKFLOW_STATES.EDITORIAL_QUEUED,
  WORKFLOW_STATES.TELEGRAM_NOTIFIED,
  WORKFLOW_STATES.READY_FOR_REVIEW,
  WORKFLOW_STATES.PUBLISHED_MANUALLY
]);

const STAGE_IDS = Object.freeze({
  SOURCE_DETECTION: "SOURCE_DETECTION",
  CHANGE_DETECTION: "CHANGE_DETECTION",
  SOURCE_INTELLIGENCE_3A: "SOURCE_INTELLIGENCE_3A",
  CONTENT_EXTRACTION_3B_3C: "CONTENT_EXTRACTION_3B_3C",
  MULTI_SOURCE_CORRELATION_3D: "MULTI_SOURCE_CORRELATION_3D",
  EXTRACTION_QUALITY_3E: "EXTRACTION_QUALITY_3E",
  RECRUITMENT_RESOLUTION: "RECRUITMENT_RESOLUTION",
  DOCUMENT_INTELLIGENCE_P1: "DOCUMENT_INTELLIGENCE_P1",
  AI_INTELLIGENCE_P2: "AI_INTELLIGENCE_P2",
  GENERATOR_DRAFT: "GENERATOR_DRAFT",
  EDITORIAL_QUEUE: "EDITORIAL_QUEUE",
  TELEGRAM_NOTIFICATION: "TELEGRAM_NOTIFICATION",
  READY_FOR_REVIEW: "READY_FOR_REVIEW",
  MANUAL_PUBLISH_GATE: "MANUAL_PUBLISH_GATE"
});

const STAGE_TO_STATE = Object.freeze({
  [STAGE_IDS.SOURCE_DETECTION]: WORKFLOW_STATES.SOURCE_DETECTED,
  [STAGE_IDS.CHANGE_DETECTION]: WORKFLOW_STATES.CHANGE_DETECTED,
  [STAGE_IDS.SOURCE_INTELLIGENCE_3A]: WORKFLOW_STATES.SOURCE_PROFILED,
  [STAGE_IDS.CONTENT_EXTRACTION_3B_3C]: WORKFLOW_STATES.CONTENT_EXTRACTED,
  [STAGE_IDS.MULTI_SOURCE_CORRELATION_3D]: WORKFLOW_STATES.CONTENT_CORRELATED,
  [STAGE_IDS.EXTRACTION_QUALITY_3E]: WORKFLOW_STATES.QUALITY_VALIDATED,
  [STAGE_IDS.RECRUITMENT_RESOLUTION]: WORKFLOW_STATES.RECRUITMENT_RESOLVED,
  [STAGE_IDS.DOCUMENT_INTELLIGENCE_P1]: WORKFLOW_STATES.DOCUMENT_ANALYZED,
  [STAGE_IDS.AI_INTELLIGENCE_P2]: WORKFLOW_STATES.AI_PREPARED,
  [STAGE_IDS.GENERATOR_DRAFT]: WORKFLOW_STATES.DRAFT_CREATED,
  [STAGE_IDS.EDITORIAL_QUEUE]: WORKFLOW_STATES.EDITORIAL_QUEUED,
  [STAGE_IDS.TELEGRAM_NOTIFICATION]: WORKFLOW_STATES.TELEGRAM_NOTIFIED,
  [STAGE_IDS.READY_FOR_REVIEW]: WORKFLOW_STATES.READY_FOR_REVIEW,
  [STAGE_IDS.MANUAL_PUBLISH_GATE]: WORKFLOW_STATES.PUBLISHED_MANUALLY
});

const PIPELINE_STAGE_ORDER = Object.freeze([
  STAGE_IDS.SOURCE_DETECTION,
  STAGE_IDS.CHANGE_DETECTION,
  STAGE_IDS.SOURCE_INTELLIGENCE_3A,
  STAGE_IDS.CONTENT_EXTRACTION_3B_3C,
  STAGE_IDS.MULTI_SOURCE_CORRELATION_3D,
  STAGE_IDS.EXTRACTION_QUALITY_3E,
  STAGE_IDS.RECRUITMENT_RESOLUTION,
  STAGE_IDS.DOCUMENT_INTELLIGENCE_P1,
  STAGE_IDS.AI_INTELLIGENCE_P2,
  STAGE_IDS.GENERATOR_DRAFT,
  STAGE_IDS.EDITORIAL_QUEUE,
  STAGE_IDS.TELEGRAM_NOTIFICATION,
  STAGE_IDS.READY_FOR_REVIEW,
  STAGE_IDS.MANUAL_PUBLISH_GATE
]);

module.exports = {
  WORKFLOW_STATES,
  STATE_SEQUENCE,
  STAGE_IDS,
  STAGE_TO_STATE,
  PIPELINE_STAGE_ORDER
};
