"use strict";

/**
 * PWP Phase 2 — Recruitment Resolution & Routing taxonomy.
 * Deterministic constants only. No AI.
 */

const ENGINE_ID = "PWP_RECRUITMENT_RESOLUTION_ENGINE";
const ENGINE_VERSION = "1.0.0";
const PHASE = "PHASE_2";

/** Deterministic resolution decisions. */
const RESOLUTION_DECISIONS = Object.freeze({
  CREATE_NEW_RECRUITMENT: "CREATE_NEW_RECRUITMENT",
  CREATE_NEW_PAGE: "CREATE_NEW_PAGE",
  UPDATE_EXISTING_PAGE: "UPDATE_EXISTING_PAGE",
  UPDATE_EXISTING_RECRUITMENT: "UPDATE_EXISTING_RECRUITMENT",
  IGNORE_DUPLICATE: "IGNORE_DUPLICATE",
  SUPERSEDED_DOCUMENT: "SUPERSEDED_DOCUMENT",
  MANUAL_REVIEW_REQUIRED: "MANUAL_REVIEW_REQUIRED",
  UNSUPPORTED: "UNSUPPORTED"
});

/** Route destinations — outputs only; never mutate pages. */
const ROUTE_DESTINATIONS = Object.freeze({
  GENERATOR: "GENERATOR",
  EDITORIAL_QUEUE: "EDITORIAL_QUEUE",
  MANUAL_REVIEW: "MANUAL_REVIEW",
  REJECTED: "REJECTED"
});

const CONFIDENCE_LEVELS = Object.freeze({
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low",
  NONE: "none"
});

const RECOMMENDED_ACTIONS = Object.freeze({
  CREATE_RECRUITMENT_PACKAGE: "CREATE_RECRUITMENT_PACKAGE",
  CREATE_GENERATOR_DRAFT: "CREATE_GENERATOR_DRAFT",
  CREATE_PAGE_DRAFT: "CREATE_PAGE_DRAFT",
  CREATE_UPDATE_DRAFT: "CREATE_UPDATE_DRAFT",
  QUEUE_EDITORIAL_REVIEW: "QUEUE_EDITORIAL_REVIEW",
  QUEUE_MANUAL_REVIEW: "QUEUE_MANUAL_REVIEW",
  IGNORE: "IGNORE",
  MARK_SUPERSEDED_AND_ROUTE_NEWEST: "MARK_SUPERSEDED_AND_ROUTE_NEWEST",
  UPDATE_RECRUITMENT_RECORD: "UPDATE_RECRUITMENT_RECORD",
  NO_ACTION: "NO_ACTION"
});

/** Canonical page section keys used for update-scope planning. */
const PAGE_SECTIONS = Object.freeze({
  SHORT_INFORMATION: "short_information",
  IMPORTANT_DATES: "important_dates",
  APPLICATION_FEE: "application_fee",
  VACANCY_DETAILS: "vacancy_details",
  ELIGIBILITY: "eligibility",
  HOW_TO_APPLY: "how_to_apply",
  IMPORTANT_LINKS: "important_links",
  EXAM_SCHEDULE: "exam_schedule",
  NOTIFICATION_VERSION: "notification_version",
  OTHER: "other"
});

module.exports = {
  ENGINE_ID,
  ENGINE_VERSION,
  PHASE,
  RESOLUTION_DECISIONS,
  ROUTE_DESTINATIONS,
  CONFIDENCE_LEVELS,
  RECOMMENDED_ACTIONS,
  PAGE_SECTIONS
};
